[openai]
api_key = "sk-proj-ULA1rxmVlrf7QzWSjGTKT3BlbkFJZHIKi6YY2HruY7rkHlPV"

[assistant]
id = "asst_fEbBTAziC93bXGhVbIbbUQ5V"
thread_id = "thread_MyngT1Kbthb0wv49ov1U1o86"

[literal]
api_key = "lsk_NiCW8sfs0HTtuBv88Uf9phzjxDhg2dfINgEtfjSXVxw"

[core]
api_key = "Hr9d5yJX8iG3kDwYVWKZqvR6zOfoaNM0"
base_url = "https://api.core.ac.uk/v3"
